[tool.black]
line-length = 79
target-version = ['py313']

[tool.mypy]
strict = true
disallow_untyped_defs = true
disallow_untyped_calls = true
disallow_incomplete_defs = true
no_implicit_optional = true
warn_unused_ignores = false

[tool.isort]
profile = "black"
line_length = 79
skip = [".venvs"]